/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle container1;
extern GHandle container2;
extern GHandle container3;
extern GHandle containerlist;
extern GHandle ghKeyboard1;
extern GHandle ghLabel1;
extern GHandle ghLabel2;
extern GHandle ghLabel3;
extern GHandle ghButton1;
extern GHandle ghButton2;

extern GHandle console1;
extern GHandle ghList1;
extern GHandle buttonlist;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

