/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

#include <stdio.h>

// GListeners
GListener glistener;

// GHandle
// Main Container (Background layer 0)
GHandle mainContainer;

// Data Container on the left side
GHandle dataContainer;
GHandle speedLabel;
GHandle rpmLabel;
GHandle batteryLabel;
GHandle menuButton;

// Console Container 
GHandle consoleContainer;
GHandle consoleWindow;

// Menu Container
GHandle menuContainer;
GHandle menuList;
GHandle returnButton;

// Map Container
GHandle mapContainer;
GHandle mapWindow;

// Bluetooth Container
GHandle bluetoothContainer;
GHandle bluetoothSearchContainer;
GHandle bluetoothSearchingContainer;
GHandle bluetoothSearchingLabel;
GHandle bluetoothDevicesContainer;
GHandle bluetoothDevicesList;
GHandle bluetoothSearchButton;

// GearsSettings Container
GHandle numberOfGearsContainer;
GHandle numberOfGearsLabel;
GHandle numberOfGearsFrontLabel;
GHandle numberOfGearsBackLabel;
GHandle numberOfGearsFNumberLabel;
GHandle numberOfGearsFPlus;
GHandle numberOfGearsFMinus;
GHandle numberOfGearsBNumberLabel;
GHandle numberOfGearsBPlus;
GHandle numberOfGearsBMinus;
GHandle numberOfGearsEnter;

GHandle numberofTeethContainer;
GHandle numberOfTeethSelectorLabel;
GHandle numberOfTeethGearLabel;
GHandle numberOfTeethLabel;
GHandle numberOfTeethGNumber;
GHandle numberOfTeethGNumberPlus;
GHandle numberOfTeethGNumberMinus;
GHandle numberOfTeethF;
GHandle numberOfTeethB;
GHandle numberOfTeethFBLabel;
GHandle numberOfTeethTNumber;
GHandle numberOfTeethTNumberPlus;
GHandle numberOfTeethTNumberMinus;
GHandle numberOfTeethEnter;

GHandle gearsStatusContainer;
GHandle gearStatusLabel;
GHandle gearStatusFrontLabel;
GHandle gearStatusBackLabel;

int gearFrontSettings[5];
int gearBackSettings[10];
char gearBuffer[5];

int speed;
char speedout[10];

static gdispImage myImage;
gdispImageError result;
int x = 0;
int y = 0;
static GDisplay* pixmap;
static pixel_t* surface;

void drawTile(int xx, int yy);

static void createMainContainer(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);
	
	// create container widget: mainContainer
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 800;
	wi.g.height = 480;
	wi.g.parent = 0;
	wi.text = "mainContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	mainContainer = gwinContainerCreate(0, &wi, 0);    
}

static void createMap(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

		
	// create container widget: mapContainer
	wi.g.show = TRUE;
	wi.g.x = 305;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "mapContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	mapContainer = gwinContainerCreate(0, &wi, 0);
    
	//create map window
  gwinSetDefaultBgColor(red_studio);
  GWindowInit windowInitStruct;
  windowInitStruct.x = 0;
  windowInitStruct.y = 0;
  windowInitStruct.width = 495;
  windowInitStruct.height = 480;
  windowInitStruct.show = TRUE;
  windowInitStruct.parent = mapContainer;
  mapWindow = gwinGWindowCreate(GDISP,NULL, &windowInitStruct);
}

static void createData(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);
		
	// create container widget: dataContainer
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 305;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	dataContainer = gwinContainerCreate(0, &wi, 0);
	
	speed = 0;
	sprintf(speedout, "%d km/h", speed);
	// Create label widget: speedLabel
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 305;
	wi.g.height = 113;
	wi.g.parent = dataContainer;
	wi.text = speedout;
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	speedLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(speedLabel, TRUE);
	gwinSetFont(speedLabel, gdispOpenFont("Georgia60"));
	gwinRedraw(speedLabel);

	// Create label widget: rpmLabel
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 114;
	wi.g.width = 305;
	wi.g.height = 71;
	wi.g.parent = dataContainer;
	wi.text = "69 RPM";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	rpmLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(rpmLabel, TRUE);
	gwinSetFont(rpmLabel, gdispOpenFont("Georgia40"));
	gwinRedraw(rpmLabel);
	
	// Create label widget: batteryLabel
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 366;
	wi.g.width = 117;
	wi.g.height = 114;
	wi.g.parent = dataContainer;
	wi.text = "100%";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	batteryLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(batteryLabel, TRUE);
	gwinSetFont(batteryLabel, gdispOpenFont("Georgia40"));
	gwinRedraw(batteryLabel);
	
	// create button widget: menuButton
	wi.g.show = TRUE;
	wi.g.x = 126; // 117 + 9
	wi.g.y = 373; // 366 + 7
	wi.g.width = 170;
	wi.g.height = 100;
	wi.g.parent = dataContainer;
  wi.text = "Settings";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	menuButton = gwinButtonCreate(0, &wi);
	gwinSetFont(menuButton, gdispOpenFont("Georgia36"));
	gwinRedraw(menuButton);
}

static void createConsole(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: consoleContainer
	wi.g.show = FALSE;
	wi.g.x = 305;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "consoleContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	consoleContainer = gwinContainerCreate(0, &wi, 0);
	
	// create button widget: consoleWindow
	GWindowInit consolewind;
	consolewind.show = TRUE;
	consolewind.x = 0;
	consolewind.y = 0;
	consolewind.width = 495;
	consolewind.height = 480;
	consolewind.parent = consoleContainer;
	consoleWindow = gwinConsoleCreate(0, &consolewind);
	gwinSetFont(consoleWindow, gdispOpenFont("DejaVuSans32"));
	gwinSetColor(consoleWindow, WHITE);
	gwinSetBgColor(consoleWindow, HTML2COLOR(0x2980B9));
}

static void createMenu(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: menuContainer
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 305;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "menuContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	menuContainer = gwinContainerCreate(0, &wi, 0);	
	
	// Create list widget: menuList
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 305;
	wi.g.height = 400;
	wi.g.parent = menuContainer;
	wi.text = "menuList";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	menuList = gwinListCreate(0, &wi, FALSE);
	gwinSetFont(menuList, gdispOpenFont("Georgia40"));
	gwinListSetScroll(menuList, scrollSmooth);
	gwinListAddItem(menuList, "Bluetooth", FALSE);
	gwinListAddItem(menuList, "Gears Settings", FALSE);
	gwinListAddItem(menuList, "Teeth Settings", FALSE);
	gwinListAddItem(menuList, "Gears Status", FALSE);
	gwinListAddItem(menuList, "Console", FALSE);
	gwinListSetSelected(menuList, 0, TRUE);
	gwinListSetSelected(menuList, 1, FALSE);
	gwinListSetSelected(menuList, 2, FALSE);
	gwinListSetSelected(menuList, 3, FALSE);
  gwinListSetSelected(menuList, 4, FALSE);
	
	// create button widget: menuButton
	wi.g.show = TRUE;
	wi.g.x = 50;
	wi.g.y = 410;
	wi.g.width = 200;
	wi.g.height = 60;
	wi.g.parent = menuContainer;
	wi.text = "Return";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	returnButton = gwinButtonCreate(0, &wi);
	gwinSetFont(returnButton, gdispOpenFont("Georgia40"));
}

static void createBluetooth(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: bluetoothContainer
	wi.g.show = FALSE;
	wi.g.x = 305;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "bluetoothContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	bluetoothContainer = gwinContainerCreate(0, &wi, 0);
	
	// create container widget: bluetoothSearchContainer
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 150;
	wi.g.parent = bluetoothContainer;
	wi.text = "bluetoothSearchContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	bluetoothSearchContainer = gwinContainerCreate(0, &wi, 0);
	
	// create container widget: bluetoothSearchingContainer
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 150;
	wi.g.width = 495;
	wi.g.height = 330;
	wi.g.parent = bluetoothContainer;
	wi.text = "bluetoothSearchingContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	bluetoothSearchingContainer = gwinContainerCreate(0, &wi, 0);
	
	// Create label widget: bluetoothSearchingLabel
	wi.g.show = TRUE;
	wi.g.x = 45;
	wi.g.y = 100;
	wi.g.width = 405;
	wi.g.height = 100;
	wi.g.parent = bluetoothSearchingContainer;
	wi.text = "Searching";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	bluetoothSearchingLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(bluetoothSearchingLabel, TRUE);
	gwinSetFont(bluetoothSearchingLabel, gdispOpenFont("Georgia60"));
	gwinRedraw(bluetoothSearchingLabel);
	
	// create container widget: bluetoothDevicesContainer
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 150;
	wi.g.width = 495;
	wi.g.height = 330;
	wi.g.parent = bluetoothContainer;
	wi.text = "bluetoothDevicesContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	bluetoothDevicesContainer = gwinContainerCreate(0, &wi, 0);
	
  // Create list widget: bluetoothDevicesList
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 330;
	wi.g.parent = bluetoothDevicesContainer;
	wi.text = "bluetoothDevicesList";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	bluetoothDevicesList = gwinListCreate(0, &wi, TRUE);
	gwinSetFont(bluetoothDevicesList, gdispOpenFont("Georgia60"));
	gwinListSetScroll(bluetoothDevicesList, scrollSmooth);
	gwinListAddItem(bluetoothDevicesList, "Device 0", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 1", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 2", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 3", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 4", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 5", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 6", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 7", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 8", FALSE);
	gwinListAddItem(bluetoothDevicesList, "Device 9", FALSE);
	gwinListSetSelected(bluetoothDevicesList, 0, TRUE);
	gwinListSetSelected(bluetoothDevicesList, 1, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 2, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 3, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 4, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 5, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 6, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 7, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 8, FALSE);
	gwinListSetSelected(bluetoothDevicesList, 9, FALSE);
	
	// create button widget: bluetoothSearchButton
	wi.g.show = TRUE;
	wi.g.x = 150;
	wi.g.y = 25;
	wi.g.width = 195;
	wi.g.height = 100;
	wi.g.parent = bluetoothSearchContainer;
	wi.text = "Search";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	bluetoothSearchButton = gwinButtonCreate(0, &wi);
	gwinSetFont(bluetoothSearchButton, gdispOpenFont("Georgia40"));
}

static void createGearsSettings(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: numberOfGearsContainer
	wi.g.show = FALSE;
	wi.g.x = 305;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "numberOfGearsContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	numberOfGearsContainer = gwinContainerCreate(0, &wi, GWIN_CONTAINER_BORDER);
	
	// Create label widget: numberOfGearsLabel
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 10;
	wi.g.width = 280;
	wi.g.height = 60;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "Number of Gears";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfGearsLabel, TRUE);
	gwinSetFont(numberOfGearsLabel, gdispOpenFont("Georgia36"));
	
	// Create label widget: numberOfGearsFrontLabel
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 80;
	wi.g.width = 160;
	wi.g.height = 60;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "Front";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsFrontLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfGearsFrontLabel, TRUE);
  gwinSetFont(numberOfGearsFrontLabel, gdispOpenFont("Georgia36"));
	
	// Create label widget: numberOfGearsBackLabel
	wi.g.show = TRUE;
	wi.g.x = 220;
	wi.g.y = 80;
	wi.g.width = 160;
	wi.g.height = 60;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "Back";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsBackLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfGearsBackLabel, TRUE);
	gwinSetFont(numberOfGearsBackLabel, gdispOpenFont("Georgia36"));
	
	// Create label widget: numberOfGearsFNumberLabel
	wi.g.show = TRUE;
	wi.g.x = 60;
	wi.g.y = 160;
	wi.g.width = 80;
	wi.g.height = 80;
	wi.g.parent = numberOfGearsContainer;
	sprintf(gearBuffer, "%d", gearFrontSettings[0]);
	wi.text = gearBuffer;
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsFNumberLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfGearsFNumberLabel, TRUE);
	gwinSetFont(numberOfGearsFNumberLabel, gdispOpenFont("Georgia36"));

	// create button widget: numberOfGearsFPlus
	wi.g.show = TRUE;
	wi.g.x = 60;
	wi.g.y = 260;
	wi.g.width = 80;
	wi.g.height = 80;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "+";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsFPlus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfGearsFPlus, gdispOpenFont("Georgia36"));

	// create button widget: numberOfGearsFMinus
	wi.g.show = TRUE;
	wi.g.x = 60;
	wi.g.y = 345;
	wi.g.width = 80;
	wi.g.height = 80;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "-";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsFMinus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfGearsFMinus, gdispOpenFont("Georgia36"));

	// Create label widget: numberOfGearsBNumberLabel
	wi.g.show = TRUE;
	wi.g.x = 260;
	wi.g.y = 160;
	wi.g.width = 80;
	wi.g.height = 80;
	wi.g.parent = numberOfGearsContainer;
	sprintf(gearBuffer, "%d", gearBackSettings[0]);
	wi.text = gearBuffer;
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsBNumberLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfGearsBNumberLabel, TRUE);
	gwinSetFont(numberOfGearsBNumberLabel, gdispOpenFont("Georgia36"));

	// create button widget: numberOfGearsBPlus
	wi.g.show = TRUE;
	wi.g.x = 260;
	wi.g.y = 260;
	wi.g.width = 80;
	wi.g.height = 80;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "+";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsBPlus = gwinButtonCreate(0, &wi);
  gwinSetFont(numberOfGearsBPlus, gdispOpenFont("Georgia36"));
	
	// create button widget: numberOfGearsBMinus
	wi.g.show = TRUE;
	wi.g.x = 260;
	wi.g.y = 345;
	wi.g.width = 80;
	wi.g.height = 80;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "-";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsBMinus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfGearsBMinus, gdispOpenFont("Georgia36"));

	// create button widget: numberOfGearsEnter
	wi.g.show = TRUE;
	wi.g.x = 380;
	wi.g.y = 350;
	wi.g.width = 100;
	wi.g.height = 100;
	wi.g.parent = numberOfGearsContainer;
	wi.text = "Enter";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfGearsEnter = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfGearsEnter, gdispOpenFont("Georgia36"));	
}

static void createTeethSettings(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: numberofTeethContainer
	wi.g.show = FALSE;
	wi.g.x = 305;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "numberofTeethContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	numberofTeethContainer = gwinContainerCreate(0, &wi, GWIN_CONTAINER_BORDER);
	
	// Create label widget: numberOfTeethSelectorLabel
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 10;
	wi.g.width = 220;
	wi.g.height = 30;
	wi.g.parent = numberofTeethContainer;
	wi.text = "Select Front or Back";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethSelectorLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfTeethSelectorLabel, TRUE);
	gwinSetFont(numberOfTeethSelectorLabel, gdispOpenFont("Georgia24"));
	
	// Create label widget: numberOfTeethGearLabel
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 50;
	wi.g.width = 150;
	wi.g.height = 30;
	wi.g.parent = numberofTeethContainer;
	wi.text = "Gear";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethGearLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfTeethGearLabel, TRUE);
	gwinSetFont(numberOfTeethGearLabel, gdispOpenFont("Georgia24"));
	
	// Create label widget: numberOfTeethLabel
	wi.g.show = TRUE;
	wi.g.x = 210;
	wi.g.y = 50;
	wi.g.width = 200;
	wi.g.height = 30;
	wi.g.parent = numberofTeethContainer;
	wi.text = "Number of Teeth";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfTeethLabel, TRUE);
	gwinSetFont(numberOfTeethLabel, gdispOpenFont("Georgia24"));
	
	// Create label widget: numberOfTeethGNumber
	wi.g.show = TRUE;
	wi.g.x = 50;
	wi.g.y = 110;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "99";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethGNumber = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfTeethGNumber, TRUE);
	gwinSetFont(numberOfTeethGNumber, gdispOpenFont("Georgia24"));
	
	// create button widget: numberOfTeethGNumberPlus
	wi.g.show = TRUE;
	wi.g.x = 100;
	wi.g.y = 90;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "+";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethGNumberPlus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethGNumberPlus, gdispOpenFont("Georgia24"));

	// create button widget: numberOfTeethGNumberMinus
	wi.g.show = TRUE;
	wi.g.x = 100;
	wi.g.y = 130;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "-";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethGNumberMinus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethGNumberMinus, gdispOpenFont("Georgia24"));

	// create button widget: numberOfTeethF
	wi.g.show = TRUE;
	wi.g.x = 250;
	wi.g.y = 10;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "F";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethF = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethF, gdispOpenFont("Georgia24"));

	// create button widget: numberOfTeethB
	wi.g.show = TRUE;
	wi.g.x = 290;
	wi.g.y = 10;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "B";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethB = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethB, gdispOpenFont("Georgia24"));

	// Create label widget: numberOfTeethFBLabel
	wi.g.show = TRUE;
	wi.g.x = 340;
	wi.g.y = 10;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "F";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethFBLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfTeethFBLabel, TRUE);
	gwinSetFont(numberOfTeethFBLabel, gdispOpenFont("Georgia24"));

	// Create label widget: numberOfTeethTNumber
	wi.g.show = TRUE;
	wi.g.x = 240;
	wi.g.y = 110;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "99";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethTNumber = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(numberOfTeethTNumber, TRUE);
	gwinSetFont(numberOfTeethTNumber, gdispOpenFont("Georgia24"));

	// create button widget: numberOfTeethTNumberPlus
	wi.g.show = TRUE;
	wi.g.x = 290;
	wi.g.y = 90;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "+";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethTNumberPlus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethTNumberPlus, gdispOpenFont("Georgia24"));

	// create button widget: numberOfTeethTNumberMinus
	wi.g.show = TRUE;
	wi.g.x = 290;
	wi.g.y = 130;
	wi.g.width = 40;
	wi.g.height = 40;
	wi.g.parent = numberofTeethContainer;
	wi.text = "-";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethTNumberMinus = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethTNumberMinus, gdispOpenFont("Georgia24"));

	// create button widget: numberOfTeethEnter
	wi.g.show = TRUE;
	wi.g.x = 410;
	wi.g.y = 90;
	wi.g.width = 70;
	wi.g.height = 70;
	wi.g.parent = numberofTeethContainer;
	wi.text = "Enter";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &belize;
	numberOfTeethEnter = gwinButtonCreate(0, &wi);
	gwinSetFont(numberOfTeethEnter, gdispOpenFont("Georgia24"));
}

static void createGearsStatus(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

  // create container widget: gearsStatusContainer
	wi.g.show = FALSE;
	wi.g.x = 305;
	wi.g.y = 0;
	wi.g.width = 495;
	wi.g.height = 480;
	wi.g.parent = mainContainer;
	wi.text = "gearsStatusContainer";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = &midnight;
	gearsStatusContainer = gwinContainerCreate(0, &wi, GWIN_CONTAINER_BORDER);
	
	// Create label widget: gearStatusLabel
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 40;
	wi.g.width = 80;
	wi.g.height = 30;
	wi.g.parent = gearsStatusContainer;
	wi.text = "Status";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	gearStatusLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(gearStatusLabel, TRUE);
	gwinSetFont(gearStatusLabel, gdispOpenFont("Georgia24"));
	
	// Create label widget: gearStatusFrontLabel
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 20;
	wi.g.width = 70;
	wi.g.height = 30;
	wi.g.parent = gearsStatusContainer;
	wi.text = "Front";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	gearStatusFrontLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(gearStatusFrontLabel, TRUE);
	gwinSetFont(gearStatusFrontLabel, gdispOpenFont("Georgia24"));

	// Create label widget: gearStatusBackLabel
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 60;
	wi.g.width = 70;
	wi.g.height = 30;
	wi.g.parent = gearsStatusContainer;
	wi.text = "Back";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &belize;
	gearStatusBackLabel = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(gearStatusBackLabel, TRUE);
	gwinSetFont(gearStatusBackLabel, gdispOpenFont("Georgia24"));
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(mainContainer);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(mainContainer);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(gdispOpenFont("DejaVuSans16"));
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);
	
	gearFrontSettings[0]=0;
	gearBackSettings[0]=0;
	
	// Create all the display pages
	createMainContainer();
	createMap();
	createData();
	createMenu();
	createConsole();
	createBluetooth();
	createGearsSettings();
	createTeethSettings();
	createGearsStatus();
	
	// Select the default display page
	guiShowPage(0);
}

void guiEventLoop(void)
{
	GEvent* pe;
	int count = 0;
	int bluetoothTimeout = 0;
	while (1) {
     if(count == 50){
				count = 0;
			  speed++;
			  if(speed == 200){
					speed = 0;
				}
			  sprintf(speedout, "%d km/h", speed);
			  gwinSetText(speedLabel, speedout, TRUE);
		 }else{
				count++;
		 }	

			if((bluetoothTimeout > 1000) && gwinGetVisible(bluetoothContainer)){
				gwinHide(bluetoothSearchingContainer);
				gwinShow(bluetoothDevicesContainer);
				bluetoothTimeout=0;
			}else{
				bluetoothTimeout++;
			}
        
        gfxSleepMilliseconds(3);
        //gdispGClear(GDISP, (LUMA2COLOR(0)));
        gwinClear(mapWindow);
        x=x+2;y=y+2;
        for(int tempx = x+4*256; tempx>-256; tempx=tempx-256)
        {
            while(tempx > 4*256)
            {
                tempx=tempx-256;
            }
            for(int tempy = y+4*256; tempy>-256; tempy=tempy-256)
            {   
                while(tempy > 4*256)
                {
                    tempy=tempy-256;
                }
                //drawTile(tempx, tempy);
                gwinDrawBox(mapWindow, tempx, tempy, 256, 256);
                
            }
        }
        //gwinRedraw(mapWindow);
        
        
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
			case GEVENT_GWIN_BUTTON:
				if (((GEventGWinButton*)pe)->gwin == menuButton) {					
						gwinHide(mapContainer);
						gwinHide(dataContainer);
						gwinShow(menuContainer);
				}else if (((GEventGWinButton*)pe)->gwin == returnButton) {
						gwinHide(consoleContainer);
						gwinHide(numberOfGearsContainer);
						gwinHide(numberofTeethContainer);
						gwinHide(gearsStatusContainer);
						gwinHide(bluetoothContainer);
						gwinHide(menuContainer);
						gwinShow(dataContainer);
				  	gwinShow(mapContainer);
				}else if (((GEventGWinButton*)pe)->gwin == bluetoothSearchButton) {
					  gwinHide(bluetoothDevicesContainer);
						gwinShow(bluetoothSearchingContainer);
					  bluetoothTimeout=0;
				}else if (((GEventGWinButton*)pe)->gwin == numberOfGearsFPlus) {
						gearFrontSettings[0]++;
						sprintf(gearBuffer, "%d", gearFrontSettings[0]);
						gwinSetText(numberOfGearsFNumberLabel, gearBuffer, TRUE);
				}else if (((GEventGWinButton*)pe)->gwin == numberOfGearsFMinus) {
						gearFrontSettings[0]--;
						sprintf(gearBuffer, "%d", gearFrontSettings[0]);
						gwinSetText(numberOfGearsFNumberLabel, gearBuffer, TRUE);
				}else if (((GEventGWinButton*)pe)->gwin == numberOfGearsBPlus) {
						gearBackSettings[0]++;
						sprintf(gearBuffer, "%d", gearBackSettings[0]);
						gwinSetText(numberOfGearsBNumberLabel, gearBuffer, TRUE);
				}else if (((GEventGWinButton*)pe)->gwin == numberOfGearsBMinus) {
						gearBackSettings[0]--;
						sprintf(gearBuffer, "%d", gearBackSettings[0]);
						gwinSetText(numberOfGearsBNumberLabel, gearBuffer, TRUE);
				}
				break;
			default:
				break;
		}
		
		if(gwinGetVisible(menuContainer)){
			gwinPrintf(consoleWindow, "Selected Item: \0331\033b%d\033B\033C\r\n", gwinListGetSelected(menuList));
			switch(gwinListGetSelected(menuList)){
				case 0:
					gwinHide(numberOfGearsContainer);
					gwinHide(numberofTeethContainer);
					gwinHide(gearsStatusContainer);
					gwinHide(consoleContainer);
				  if(!gwinGetVisible(bluetoothContainer)){
						gwinShow(bluetoothContainer);
					}
					break;
				case 1:
					gwinHide(bluetoothContainer);
					gwinHide(numberofTeethContainer);
					gwinHide(gearsStatusContainer);
					gwinHide(consoleContainer);
					if(!gwinGetVisible(numberOfGearsContainer)){
						gwinShow(numberOfGearsContainer);
					}
				  break;
				case 2:
					gwinHide(numberOfGearsContainer);
					gwinHide(bluetoothContainer);
					gwinHide(gearsStatusContainer);
					gwinHide(consoleContainer);
					if(!gwinGetVisible(numberofTeethContainer)){
						gwinShow(numberofTeethContainer);
					}
					break;
				case 3:
					gwinHide(numberOfGearsContainer);
					gwinHide(bluetoothContainer);
					gwinHide(numberofTeethContainer);
					gwinHide(consoleContainer);
					if(!gwinGetVisible(gearsStatusContainer)){
						gwinShow(gearsStatusContainer);
					}
					break;
				case 4:
					gwinHide(numberOfGearsContainer);
					gwinHide(bluetoothContainer);
					gwinHide(numberofTeethContainer);
					gwinHide(gearsStatusContainer);
					if(!gwinGetVisible(consoleContainer)){
						gwinShow(consoleContainer);
					}
					break;
			}
		}
	}
}

void drawTile(int xx, int yy)
{
    coord_t	swidth, sheight;
    swidth = gdispGetWidth();
	sheight = gdispGetHeight();
    gdispImageOpenFile(&myImage, "maptile_bmp.bmp");
	gdispImageDraw(&myImage, xx, yy, swidth, sheight, 0, 0);
    gdispImageClose(&myImage);
}

