/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle ghKeyboard1;
GHandle ghLabel1;
GHandle ghLabel2;
GHandle ghLabel3;

GHandle ghMapWindow;

// Fonts
font_t dejavu_sans_16;
font_t dejavu_sans_10;
font_t dejavu_sans_32_anti_aliased;
font_t dejavu_sans_12_anti_aliased;


static gdispImage myImage;
static gdispImage myImage2;
gdispImageError result;
int x = 0;
int y = 0;
static GDisplay* pixmap;
static pixel_t* surface;

void drawTile(int xx, int yy);


static void createPagePage0(void)
{
    
    
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 800;
	wi.g.height = 480;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);
    
    //create map window
    gwinSetDefaultBgColor(red_studio);
    GWindowInit windowInitStruct;
    windowInitStruct.x = 305;
    windowInitStruct.y = 0;
    windowInitStruct.width = 495;
    windowInitStruct.height = 480;
    windowInitStruct.show = TRUE;
    windowInitStruct.parent = ghContainerPage0;
    
    ghMapWindow = gwinGWindowCreate(GDISP,NULL, &windowInitStruct);
    
    
    
    /*
	// Create keyboard widget: ghKeyboard1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 250;
	wi.g.width = 800;
	wi.g.height = 200;
	wi.g.parent = ghContainerPage0;
	wi.text = "Keyboard1";
	wi.customDraw = gwinKeyboardDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghKeyboard1 = gwinKeyboardCreate(0, &wi);
*/
	// Create label widget: ghLabel1
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 50;
	wi.g.width = 120;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "WOW Texts!";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel1, FALSE);
	gwinSetFont(ghLabel1, dejavu_sans_10);
	gwinRedraw(ghLabel1);

	// Create label widget: ghLabel2
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 170;
	wi.g.width = 690;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "W00T 32 Km/h";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel2 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel2, FALSE);
	gwinSetFont(ghLabel2, dejavu_sans_32_anti_aliased);
	gwinRedraw(ghLabel2);
/*
	// Create label widget: ghLabel3
	wi.g.show = TRUE;
	wi.g.x = 30;
	wi.g.y = 100;
	wi.g.width = 120;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Sans 12 AA";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = &black;
	ghLabel3 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel3, FALSE);
	gwinSetFont(ghLabel3, dejavu_sans_12_anti_aliased);
	gwinRedraw(ghLabel3);
    
    */
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	/*
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");
	dejavu_sans_10 = gdispOpenFont("DejaVuSans10");
	dejavu_sans_32_anti_aliased = gdispOpenFont("DejaVuSans32_aa");
	dejavu_sans_12_anti_aliased = gdispOpenFont("DejaVuSans12_aa");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);
	*/

}

void guiEventLoop(void)
{
	GEvent* pe;
	
	
	coord_t		width, height;
  coord_t		i, j;

	width = gdispGetWidth();
  height = gdispGetHeight();
	pixmap = gdispPixmapCreate(800, 480);
  surface = gdispPixmapGetBits(pixmap);
	
	
	
	while (1) {
        
        
        gfxSleepMilliseconds(300);
        //gdispGClear(GDISP, (LUMA2COLOR(0)));
        //gdispGClear(pixmap, black_studio);
				gdispFillArea(0,0,800,480,black_studio);
        x=x+2;y=y+2;
		/*
        for(int tempx = x+4*256; tempx>-256; tempx=tempx-256)
        {
            while(tempx > 4*256)
            {
                tempx=tempx-256;
            }
            for(int tempy = y+4*256; tempy>-256; tempy=tempy-256)
            {   
                while(tempy > 4*256)
                {
                    tempy=tempy-256;
                }
                //drawTile(tempx, tempy);
                gdispGDrawBox(pixmap, tempx, tempy, 256, 256, white_studio);
                
            }
        }
				
				*/
				
				gdispGDrawLine(pixmap, 0, 0 ,700, 450, white_studio);
        //gwinRedraw(ghMapWindow);
				surface[200]= RGB2COLOR(122,122,122);
        gdispBlitArea(0, 0, 800, 480, surface);
				
        
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		}
        


	}
}

void drawTile(int xx, int yy)
{
    coord_t	swidth, sheight;
    swidth = gdispGetWidth();
	sheight = gdispGetHeight();
    gdispImageOpenFile(&myImage, "maptile_bmp.bmp");
	gdispImageDraw(&myImage, xx, yy, swidth, sheight, 0, 0);
    gdispImageClose(&myImage);
}

